### ISSUE TITLE
how do u change placement mode to destructing mode

### ISSUE THREAD

**Issue by zacharyhenry** [Theta-Dev/ConstructionWand#38]
sneak button not opening gui 
![2021-09-14_17 24 49](https://user-images.githubusercontent.com/49297302/133342159-33de7531-40ab-40e4-bac9-63a19c7f1b81.png)

**Comment by zacharyhenry** [comment]
i fiqured it out its Lshift+Lctrl+rightclick 👍

**Comment by Theta-Dev** [comment]
You need to hold SHIFT+CTRL and right click to open the wand gui.
There is also a shortcut for changing wand modes: hold down SHIFT and left-click with the wand.

**Comment by zacharyhenry** [comment]
thanks for helping i saw ur instructions i got the case of the dumbs :)

**Comment by Theta-Dev** [comment]
I had the issue that opening a GUI while sneaking at an edge causes you to fall after you close the UI.

That's why I had to change the key combination, because I kept dying in Skyblock. You can change it in the client config file if you want though.
