### ISSUE TITLE
Wand treats half slabs as replaceable blocks and replaces them

### ISSUE THREAD

**Issue by Darkosto** [Theta-Dev/ConstructionWand#40]
https://github.com/DarkPacks/SkyFactory-One/issues/8

MC: 1.16.5
Forge: 36.2.8
Construction Wands: 2.2

Hello! 

Would you consider adding the ability to place slabs under already placed top slabs? Currently, when using the wand to place bottom slabs under top slabs it will delete the top slab. I've attached an issue from my tracker which should help give a bit more information.

Thanks!
Darkosto

**Comment by Theta-Dev** [comment]
I have tested placing slabs with the wand and I could not get it to delete any slabs while placing. You dont have the red destruction core activated, have you?

The only possible issue with slab placement is that the wands think in blocks. So placing a slab above a bottom slab will place a new bottom slab above it, leaving space. Same with placing a bottom slab under a top slab.

Here you see my test. The slab in the middle was extended top and bottom. The blocks in the middle are for reference.

![image](https://user-images.githubusercontent.com/19636565/137460863-dc488c48-caa7-4208-b677-71a2fd57e72e.png)

**Comment by Darkosto** [comment]
I managed to figure out how to get it to happen reliably, here's a video clip if you're interested: https://clips.twitch.tv/PlacidCharmingLlamaRalpherZ-P3vbFaY9XrGAONKF

**Comment by Theta-Dev** [comment]
Okay, that looks like the wand senses half-slabs as empty space. It even shows the placement preview over the slabs. I'll try to reproduce it tomorrow.

**Comment by Theta-Dev** [comment]
Thanks for the video, I could reproduce the issue.
It appearently only overrides slabs if you have the "Replace" option activated, meaning it treats slabs as replaceable blocks.
I will work on a fix.

![image](https://user-images.githubusercontent.com/19636565/138404925-9c40a3b1-c345-48e2-9028-ea00712b8347.png)

**Comment by Theta-Dev** [comment]
Alright, I have published Construction Wand 2.4, which fixes the issue.

**Comment by Darkosto** [comment]
This update works great! Thank you for the update
