### ISSUE TITLE
does ur mod support macaw roofs

### ISSUE THREAD

**Issue by zacharyhenry** [Theta-Dev/ConstructionWand#41]
it makes ghost blocks sometimes when im building 

1.16.5

36.2.4 modloader

mod version
1.16.5-2.2

modpack    enigmatica6 -5.17
![2021-10-21_14 22 47](https://user-images.githubusercontent.com/49297302/138343917-0bf5dad8-9293-49d5-97e7-f2d9c28038bb.png)

**Comment by Theta-Dev** [comment]
You mean the steep roof tiles from Macaw's Roofs? Since these are 2 blocks tall, construction wands cannot handle them.
The mod tries to place a block in every space it can, which results in roof tiles placed into eachother.
