### ISSUE TITLE
Allow wand to pull from backpacks and other inventories

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Theta-Dev/ConstructionWand#43]
Building Gadgets can pull blocks from inventories carried by the player such as backpacks, dank storage, and black hole talismans. This is convenient as it cuts down on inventory management.

It may be possible to copy the code from Building Gadgets since it's under the MIT licence.

**Comment by Theta-Dev** [comment]
Construction Wands can do that, too. I have explicitly tested the Botania black hole talisman and dank storage units and they both work.

In fact, all mod items that implement the Forge ItemHandler capability work with CW.
Botania has its own API which is supported as well.

**Comment by Theta-Dev** [comment]
If there is a specific item container that is not supported, please mention it (plus mod + minecraft version) and I can look into it.

**Comment by AvremelM** [comment]
@Theta-Dev Does it make sense that the wand can pull from a Sophisticated Backpacks backpack that's in my inventory, but can't pull from it when I'm wearing it in a Curios slot?

That's not intentional, I hope?

ConstructionWand: 1.18.2-2.7
Sophisticated Backpacks: 3.18.29.718
(in ATM7-TTS modpack)
