### ISSUE TITLE
Support Quark's lock orientation mode

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Theta-Dev/ConstructionWand#44]
With Quark installed, presing K (by default) enables orientation lock mode. Any directional blocks like stairs are placed in one direction until the mode is disabled, instead of using the player's current direction.

It would be nice of construction wands respected this setting when it was enabled.

**Comment by Theta-Dev** [comment]
ConstructionWands have a similar mode. You can open the wand GUI and change the direction from _Player_ to _Target_.
This places blocks in the same orientation as the block you are targeting. See the pictures in the readme for explaination.

So you can build a roof with stair blocks by placing the first layer with Quark's direction lock and then extending that with the wand.

There is no way I could integrate the direction lock from Quark though. Quark has no API for that, so no other mod can tell if the lock is enabled.

**Comment by TheDeviantCrafter** [comment]
The old better builders wands mod supported this, but I believe that was
more of a happy accident. The mod would simply emulate placing blocks as if
the player did normally. Construction Wands seems to have more control over
block placement.
