### ISSUE TITLE
Add in-game documentation using JEI's information recipe type

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Theta-Dev/ConstructionWand#45]
JEI supports an information recipe type. Checking the recipes of a wand would also show an info box containing information about wands. The mod's Curseforge page mentions quite a few advanced features that I don't think most people know about.

**Comment by Theta-Dev** [comment]
I have implemented ingame documentation with JEI. Here is a preview:

![image](https://user-images.githubusercontent.com/19636565/145261911-830ad780-f080-4eae-876d-81067b7ba4b9.png)
![image](https://user-images.githubusercontent.com/19636565/145261965-2f5d2545-b155-47bc-9d14-ca461d184132.png)

It will be published in the next CW update (2.5)

**Comment by Theta-Dev** [comment]
Released CW 2.5 which fixes the issue.
