### ISSUE TITLE
Link in config file

### ISSUE THREAD

**Issue by Dryelo** [Theta-Dev/ConstructionWand#49]
hi there, just a minor thing.

The link you provide in the constructionwand-client.toml file (where to look up the key codes) doesn't exist anymore.
I suppose this is where you want to go:  https://www.glfw.org/docs/latest/group__keys.html

Nice mod, btw... cheers!

Edit: I just saw I'm not playing with the latest version. Sorry if this is alreay fixed.

**Comment by Theta-Dev** [comment]
I have just tested the link from the config file and it works: https://www.glfw.org/docs/3.3/group__keys.html

https://github.com/Theta-Dev/ConstructionWand/blob/aeb0e32af4454bd2b30620bdce156080d5a8edfa/src/main/java/thetadev/constructionwand/basics/ConfigClient.java#L22

Maybe there was a temporary issue with the site or something.
