### ISSUE TITLE
Provide a Chinese translation file

### ISSUE THREAD

**Issue by chindev2012** [Theta-Dev/ConstructionWand#53]
### zh_cn.json

{
  "item.constructionwand.stone_wand": "石制手杖",
  "item.constructionwand.iron_wand": "铁制手杖",
  "item.constructionwand.diamond_wand": "钻石手杖",
  "item.constructionwand.infinity_wand": "无尽手杖",
  "item.constructionwand.core_angel": "天使手杖核心",
  "item.constructionwand.core_destruction": "破坏手杖核心",

  "constructionwand.tooltip.blocks": "最大 %d 块",
  "constructionwand.tooltip.shift": "按住[SHIFT]",
  "constructionwand.tooltip.cores": "手杖核心:",
  "constructionwand.tooltip.core_tip": "将核心与你的手杖组合在一个制作网格中",

  "constructionwand.option.cores": "手杖核心",
  "constructionwand.option.cores.constructionwand:default": "建筑核心",
  "constructionwand.option.cores.constructionwand:default.desc": "在面向你的一侧扩展你的建筑物",
  "constructionwand.option.cores.constructionwand:core_angel": "§6天使核心",
  "constructionwand.option.cores.constructionwand:core_angel.desc": "在方块的背面放置，还可以悬空放置方块",
  "constructionwand.option.cores.constructionwand:core_destruction": "§c破坏核心",
  "constructionwand.option.cores.constructionwand:core_destruction.desc": "破坏面向你一侧的方块",

  "constructionwand.option.lock": "锁定: ",
  "constructionwand.option.lock.horizontal": "§a左/右",
  "constructionwand.option.lock.horizontal.desc": "在起始方块的前面延伸一行水平方块",
  "constructionwand.option.lock.vertical": "§a上/下",
  "constructionwand.option.lock.vertical.desc": "在起始方块的前面延伸一列竖直方块",
  "constructionwand.option.lock.northsouth": "§6北/南",
  "constructionwand.option.lock.northsouth.desc": "在起始方块的上面，向南 / 北方向延伸一行",
  "constructionwand.option.lock.eastwest": "§6东/西",
  "constructionwand.option.lock.eastwest.desc": "在起始方块的上面，向东 / 西方向延伸一行",
  "constructionwand.option.lock.nolock": "§c无",
  "constructionwand.option.lock.nolock.desc": "从起始方块向任意一面延伸",

  "constructionwand.option.direction": "方向: ",
  "constructionwand.option.direction.target": "§6目标",
  "constructionwand.option.direction.target.desc": "放置的方块方向与目标方块的方向相同",
  "constructionwand.option.direction.player": "§a玩家",
  "constructionwand.option.direction.player.desc": "放置的方块面向玩家",

  "constructionwand.option.replace": "替换: ",
  "constructionwand.option.replace.yes": "§a是",
  "constructionwand.option.replace.yes.desc": "替换某些方块，例如流体、雪、高草丛",
  "constructionwand.option.replace.no": "§c否",
  "constructionwand.option.replace.no.desc": "不要替换块",

  "constructionwand.option.match": "匹配: ",
  "constructionwand.option.match.exact": "§a精确",
  "constructionwand.option.match.exact.desc": "只放置完全相同的方块",
  "constructionwand.option.match.similar": "§6模糊",
  "constructionwand.option.match.similar.desc": "相似的方块被认为是相同的（草方块 / 泥土类型）",
  "constructionwand.option.match.any": "§c任意",
  "constructionwand.option.match.any.desc": "匹配任意块",

  "constructionwand.option.random": "随机: ",
  "constructionwand.option.random.yes": "§a是",
  "constructionwand.option.random.yes.desc": "随机放置快捷栏中的方块",
  "constructionwand.option.random.no": "§c否",
  "constructionwand.option.random.no.desc": "不会随机放置方块",

  "constructionwand.description.wand": "%1$s 最多可以在面向你的建筑物一侧放置 %2$d 个方块，并持续 %3$s。\n\n按住 %5$s 并滚动鼠标来更改放置方向（水平、垂直、北 /南, 东/西, 无)。\n\n使用 %6$s§9+右键单击§0 打开选项屏幕。\n\n§5§n撤消§0§r\n按住 §9潜行键+§0 %4$s 在查看方块时会显示你放置的最后一个方块，并在它们周围带有绿色边框。 §9潜行键+§0%4$s§9+右击§0其中任何一个都将撤消操作，将所有物品归还给你。 如果你使用了破坏核心，它将恢复这些方块。\n\n§5§n容器§0§r\n潜影盒、捆绑包和来自其他模组的许多容器可以为手杖提供建筑方块。\n\n§5 §n副手优先§0§r\n副手有方块会放置它们而不是你正在查看的方块。",
  "constructionwand.description.durability.limited": "用于 %d 个方块",
  "constructionwand.description.durability.unlimited": "无限制",
  "constructionwand.description.key.sneak": "潜行",
  "constructionwand.description.key.sneak_opt": "潜行+%s",
  "constructionwand.description.core": "§5§n安装§0§r\n将你的新核心和手杖放在一个制作网格中来安装它。 要在核心之间切换，请按住 %s 并用你的手杖左键单击空白区域或使用选项屏幕。",
  "constructionwand.description.core_angel": "天使核心在你面对的方块（或一排方块）另一侧放置一个方块。 最大距离取决于手杖等级。 右键单击空白空间以在半空中放置一个方块。 为此，你需要将要放置的方块放在副手上。",
  "constructionwand.description.core_destruction": "破坏核心会破坏面向你一侧的方块（不包含砖块实体）。 最大块数取决于手杖等级。 被破坏的方块将消失在虚空中，如果操作错误，你可以使用撤消功能。",

  "stat.constructionwand.use_wand": "放置方块需要使用手杖"
}

**Comment by ruifengx** [comment]
IMO this translation really need substantial improvements before being adopted (if at all). Note, for example, some occurrences of the word "block" is translated as "块", while usually it should be "方块". I suggest considering the translation in [CFPAOrg/Minecraft-Mod-Language-Package](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases) instead, which I personally find reliable and with high quality.

**Comment by Theta-Dev** [comment]
I cant just include the translation from this project in my mod, since it is published under a non-compatbile CC BY-NC-SA license. I could ask the project owner if they allow publishing the translation under MIT license.

**Comment by AnzhiZhang** [comment]
Discussing: https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/discussions/2042

**Comment by Theta-Dev** [comment]
closing as this was resolved in #59
