### ISSUE TITLE
Angel core upgrade not working

### ISSUE THREAD

**Issue by Nevrai** [Theta-Dev/ConstructionWand#54]
I got the angel core upgrade on my diamond wand, but no matter what I do, I can’t seem to place a block mid-air. I am holding the blocks in my off-hand. I’ve tried each of the different modes, and I’ve tried sneaking and not sneaking, as well as flying (with a jetpack) and not flying.

### Versions
* **Modpack:** [All the Mods 7](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7) (0.4.25—latest)
* **Minecraft:** 1.18.2
* **Forge:** 40.1.68
* **Construction Wand:** 2.7 (latest for 1.18.2)

**Comment by Theta-Dev** [comment]
Sorry, but I cant reproduce your issue. I have taken a Diamond Wand, crafted it together with an angel core, enabled angel mode (Sneak+left click or in the menu), took blocks in my off-hand and right-clicked (not sneak-right-clicked) empty space.
I also tried flying in Survival with a Botania Flügel Tiara and the angel wand works here, too.

**Comment by Nevrai** [comment]
I tried everything. Everything except sneak+left-clicking. Whoops! In my defence, the [mod page](https://www.curseforge.com/minecraft/mc-mods/construction-wand) says “Sneak+Right click to activate angel mode.” That should probably be updated.

**Comment by Theta-Dev** [comment]
Oh yes, you are right. This line comes from the first versions of this mod which did not have the GUI. I'll correct that.

Edit: yeah, I updated the entire description page after this update - just not the header 🙈
