### ISSUE TITLE
[Suggestion] Fuzzy mode

### ISSUE THREAD

**Issue by Nevrai** [Theta-Dev/ConstructionWand#55]
I think that a fuzzy mode for the construction wand (i.e., placing blocks on all blocks rather than just blocks of the same variety) would be incredibly useful, and it’s the one feature I’ve been sad not to have in Construction Wand.

**Comment by Theta-Dev** [comment]
That feature already exists, just open the wand GUI (Sneak + Right click) and set the option `Matching` to `Any`.

**Comment by Nevrai** [comment]
Sneak + right-click doesn’t open any GUI. I’m playing 1.18.2 (version 2.7). Is this not a feature in the 1.18.2 version of the mod?

**Comment by Theta-Dev** [comment]
you have to sneak + right click into empty space.

**Comment by Nevrai** [comment]
That’s what I did. I tried it many times, but nothing happens.

**Comment by Nevrai** [comment]
I solved it! Shift Opt GUI was enabled in the config, meaning I had to press the opt key, which was set to left ctrl, as well as sneak to open the GUI. Turning this off lets me open the GUI! Awesome!

**Comment by Theta-Dev** [comment]
Oh sorry, I forgot to mention that you have to hold down left control, too. I added this feature because I kept dying in skyblock when the GUI accidentally opened during sneaking.

**Comment by Nevrai** [comment]
Yeah, no worries! Perhaps you should disable that option by default. A tooltip on the construction wand would also be helpful to people like me who had no idea the GUI was a thing!
