### ISSUE TITLE
Suggestion: Trowel Core

### ISSUE THREAD

**Issue by DreamThorn** [Theta-Dev/ConstructionWand#65]
It would be useful to have the functionality of the Trowel from Quark in a building wand.

It would essentially build with blocks randomly selected from your hotbar, weighted by how many slots on your hotbar contain that block.

It could also add an extra rotation mode that allows the blocks to be rotated randomly.

**Comment by Theta-Dev** [comment]
This functionality already exists, you have to enable Random mode in the wand GUI.

You probably also want to set Matching to Any so you can build on top of the random blocks you placed.

**Comment by DreamThorn** [comment]
Sorry, but thanks.

I wasn't aware of the GUI, since there's no key bind for, or tool tip about it.  But since I now knew to look for it, I found the info in JEI.
