### ISSUE TITLE
Crash to Desktop - Botania + Construction Wands

### ISSUE THREAD

**Issue by atlgeek007** [Theta-Dev/ConstructionWand#66]
https://gist.github.com/atlgeek007/1cacc40cb844f0781237e51f94768151

Whenever I have Botania items in my inventory (not even equipped, just in my inventory) and I attempt to equip a construction wand, I crash to desktop with the above errors.

I have also opened an issue with Botania - https://github.com/VazkiiMods/Botania/issues/4290

**Comment by Theta-Dev** [comment]
I see the issue. I have built the 1.19 version of ConstructionWand with the 1.18 version of the Botania API, thinking that they would not change the API.

It looks like they renamed the interface from `IBlockProvider` to `BlockProvider` so it is not compatibile any more.

I will fix it tomorrow.

**Comment by Theta-Dev** [comment]
Published Construction Wand 2.9 which fixes the issue
